_extends: .github

repository:
  name: codeowners01

collaborators:
  - username: aliok
    permission: admin

  - username: erenmehmetok
    permission: push

  - username: zeynepizelok
    permission: push
